sudo: required

services:
  - docker

before_install:
  - docker images

script:
  - docker build . -t jiangz/rust-musl-builder

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jiangz/rust-musl-builder
    fi

